### PR TITLE
Update and unpin some dependencies

### PR DESCRIPTION
**Pull request by PerchunPak**
Our dependencies in `main` group were pinned since adding the poetry (which means - they were pinned always). This is a bad practice because it doesn't allow the user to install any other version of the used by us library.

I also hope that bumping `coverage` dependency will fix [flaky Windows tests](https://github.com/py-mine/mcstatus/actions/runs/5071761765/jobs/9108556201#step:4:24) that are pretty randomly crash with `AttributeError: 'NoneType' object has no attribute 'startswith'` (it points to coverage.py files).

---

I also didn't update tox to v4 because of two reasons:

1. `tox-poetry` was deprecated and there is no stable version that supports v4. (Deprecation because Poetry included official support of tox)
2. We have [a deprecation warning](https://github.com/py-mine/mcstatus/actions/runs/5071761765/jobs/9108555752#step:4:357) in CI, which would be an error in v4.

I personally have no motivation to fix these issues and I would better go with #488 as solution for those.

---

Python version was bumped from `3.8.0+` to `3.8.1+` because of similar bump in

### CODE REVIEW

File: pyproject.toml [hunk 1]
```diff
@@ -29,62 +29,62 @@ packages = [
...
+asyncio-dgram = "^2.1.2"
+dnspython = "^2.3.0"
 
 [tool.poetry.group.dev.dependencies]
-pre-commit = "^3.2.2"
-tox = "^3.26.0"
-tox-poetry = ">=0.4.1,<0.6.0"
+pre-commit = "^3.3.2"
+tox = "^3.28.0"
+tox-poetry = "0.5.0" # deprecated, no sense in `^`
```
Comment (kevinkjt2000) [inline pyproject.toml:39]: Also, I have staged local changes that remove tox entirely once the automated releases are happening in GitHub actions. So, we do not need to concern ourselves with tox-related things.

**Review by kevinkjt2000 — APPROVED** [review]

**Comment by kevinkjt2000** [comment]
I did not take time to investigate the linter error from pyright, but the dependencies look good.

**Comment by PerchunPak** [comment]
> I did not take time to investigate the linter error from pyright, but the dependencies look good.

I already fix those in a2d553180d61b9a492e1fa9d98a20fd134255d8c, so I will just cherry-pick the commit.

File: pyproject.toml (hunk 1 above)
Comment (kevinkjt2000) [reply pyproject.toml:39]: It means that I have incomplete local progress for #488
